apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-product-price-deployment
  labels:
    app: go-product-price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-product-price
  template:
    metadata:
      labels:
        app: go-product-price
    spec:
      containers:
        - name: go-product-price
          image: jmlero/go-product-price:v0.1
          ports:
            - containerPort: 8080
