apiVersion: v1
kind: Service
metadata:
  name: go-product-price-service
spec:
  type: LoadBalancer
  selector:
    app: go-product-price
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
